<?php
/**
 * Plugin Name: {{PLUGIN_NAME}} Gold Engine
 * Plugin URI: https://kainex.pl
 * Description: This is automatically generated by the {{PLUGIN_NAME}} plugin to increase performance of the chat. Please do not delete it because it may seriously break the chat. It is automatically deleted after deleting {{PLUGIN_NAME}} plugin.
 * Author: Kainex
 * Author URI: https://kainex.pl
 * License: GPL2
 * Network: true
*/

use Kainex\WiseChat\Container;
use Kainex\WiseChat\Endpoints\MessagesEndpoint;
use Kainex\WiseChat\Endpoints\UserCommandEndpoint;
use Kainex\WiseChat\Loader;

if (!headers_sent()) {
	header('Content-Type: text/html');
	header('Cache-Control: no-cache');
	header('Pragma: no-cache');
}

if (!isset($_GET['wc-gold-engine'])) {
    return;
}

if (!defined('WP_PLUGIN_DIR')) {
    exit;
}

if (!defined('DOING_AJAX')) {
	define('DOING_AJAX', true);
}

if (!isset($_REQUEST['action'])) {
    http_response_code(400);
    die(json_encode(['error' => 'No action specified']));
}

require_once(ABSPATH.WPINC.'/default-constants.php');
wp_cookie_constants();
require_once(ABSPATH.WPINC.'/pluggable.php');

$GLOBALS['wp_rewrite'] = new WP_Rewrite();
$GLOBALS['wp_query'] = new WP_Query();

require_once('{{PLUGIN_DIR}}src/Loader.php');
Loader::install();

// TODO: check if there are new messages sooner

add_action('plugins_loaded', function() {
	// the code must be executed here because some WP function generate warnings: WP_User_Query::query()
	$action = $_REQUEST['action'];
	if ($action === 'wise_chat_messages_endpoint') {
		$container = Container::getInstance();

		/** @var MessagesEndpoint $endpoint */
		$endpoint = $container->get(MessagesEndpoint::class);
		$endpoint->messagesEndpoint();
	} else if ($action === 'wise_chat_prepare_image_endpoint') {
		$container = Container::getInstance();

		/** @var UserCommandEndpoint $endpoint */
		$endpoint = $container->get(UserCommandEndpoint::class);
		$endpoint->prepareImageEndpoint();
	} else if ($action === 'check') {
		die('OK');
	} else {
		http_response_code(400);
		die(json_encode(['error' => 'Invalid action']));
	}
}, 1);
